"""Add has_contributed flag to user

Revision ID: 232d57a1d555
Revises: 90df2836e578
Create Date: 2025-06-10 00:58:18.811994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '232d57a1d555'
down_revision: Union[str, None] = '90df2836e578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_contributed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_contributed')
    # ### end Alembic commands ###
