"""Make api_key_id nullable in usage_events

Revision ID: 3c5b9d7e4f2a
Revises: 5d1a2b3c4e5f
Create Date: 2025-09-06 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c5b9d7e4f2a'
down_revision: Union[str, None] = '5d1a2b3c4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_key_usage_events', 'api_key_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Downgrading may fail if there are NULL values in the column.
    op.execute('UPDATE api_key_usage_events SET api_key_id = 0 WHERE api_key_id IS NULL')
    op.alter_column('api_key_usage_events', 'api_key_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###