"""Add source to contribution

Revision ID: 3d9f1a2b8c7e
Revises: 2a1b3c4d5e6f
Create Date: 2025-09-09 14:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d9f1a2b8c7e'
down_revision: Union[str, None] = '2a1b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributions', sa.Column('source', sa.String(), server_default='cli', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contributions', 'source')
    # ### end Alembic commands ###