"""Add lifetime earnings and claims table

Revision ID: 45d12a3b987c
Revises: 609112a1767b
Create Date: 2025-06-25 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45d12a3b987c'
down_revision: Union[str, None] = '609112a1767b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('total_lum_earned', sa.Float(), nullable=False, server_default='0.0'))
    op.create_table('claim_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_claimed', sa.Float(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_transactions_id'), 'claim_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_claim_transactions_transaction_hash'), 'claim_transactions', ['transaction_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_transactions_transaction_hash'), table_name='claim_transactions')
    op.drop_index(op.f('ix_claim_transactions_id'), table_name='claim_transactions')
    op.drop_table('claim_transactions')
    op.drop_column('accounts', 'total_lum_earned')
    # ### end Alembic commands ###