"""Add verification and plan to business models

Revision ID: 5034641c66cf
Revises: 84ecef8f462d
Create Date: 2025-08-23 09:16:41.913539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5034641c66cf'
down_revision: Union[str, None] = '84ecef8f462d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # I've added server_default='false' to handle existing rows.
    op.add_column('business_users', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('business_users', sa.Column('verification_token', sa.String(), nullable=True))
    # I've added server_default='free' to handle existing rows.
    op.add_column('companies', sa.Column('plan', sa.String(), nullable=False, server_default='free'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'plan')
    op.drop_column('business_users', 'verification_token')
    op.drop_column('business_users', 'is_verified')
    # ### end Alembic commands ###