"""Add transaction_hash to Contribution model

Revision ID: 609112a1767b
Revises: a398557309a7
Create Date: 2025-06-23 17:24:14.086252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '609112a1767b'
down_revision: Union[str, None] = 'a398557309a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributions', sa.Column('transaction_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_contributions_transaction_hash'), 'contributions', ['transaction_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contributions_transaction_hash'), table_name='contributions')
    op.drop_column('contributions', 'transaction_hash')
    # ### end Alembic commands ###
