"""rename content_hash to embedding

Revision ID: 6837691c889e
Revises: c07205002d7a
Create Date: 2025-06-17 21:35:55.606014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6837691c889e'
down_revision: Union[str, None] = 'c07205002d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributions', sa.Column('content_embedding', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_contributions_content_hash'), table_name='contributions')
    op.drop_column('contributions', 'content_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributions', sa.Column('content_hash', sa.VARCHAR(), nullable=True))
    op.create_index(op.f('ix_contributions_content_hash'), 'contributions', ['content_hash'], unique=False)
    op.drop_column('contributions', 'content_embedding')
    # ### end Alembic commands ###
