"""Add reward_multiplier to User model

Revision ID: 6e6c8f8defe0
Revises: 6f02f916010e
Create Date: 2025-08-21 18:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e6c8f8defe0'
down_revision: Union[str, None] = '6f02f916010e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reward_multiplier', sa.Float(), nullable=False, server_default='1.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reward_multiplier')
    # ### end Alembic commands ###