"""Create unlocked_contributions and api_key tracking

Revision ID: 8a9b0c1d2e3f
Revises: 7a8b9c0d1e2f
Create Date: 2025-08-27 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a9b0c1d2e3f'
down_revision: Union[str, None] = '7a8b9c0d1e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unlocked_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('contribution_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contribution_id'], ['contributions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unlocked_contributions_id'), 'unlocked_contributions', ['id'], unique=False)
    op.add_column('api_keys', sa.Column('key_prefix', sa.String(length=8), nullable=False))
    op.create_unique_constraint('uq_api_keys_key_prefix', 'api_keys', ['key_prefix'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_api_keys_key_prefix', 'api_keys', type_='unique')
    op.drop_column('api_keys', 'key_prefix')
    op.drop_index(op.f('ix_unlocked_contributions_id'), table_name='unlocked_contributions')
    op.drop_table('unlocked_contributions')
    # ### end Alembic commands ###