"""create_payout_batch_models_and_remove_claims

Revision ID: 987be0a76bc9
Revises: 5034641c66cf
Create Date: 2025-08-23 21:43:51.773270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '987be0a76bc9'
down_revision: Union[str, None] = '5034641c66cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payout_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'PROCESSING', 'COMPLETED', name='batch_status_enum'), nullable=False),
    sa.Column('total_amount_usd', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payout_batches_id'), 'payout_batches', ['id'], unique=False)
    op.create_table('batch_payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='payout_status_enum'), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['payout_batches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_payouts_id'), 'batch_payouts', ['id'], unique=False)
    op.create_index(op.f('ix_batch_payouts_transaction_hash'), 'batch_payouts', ['transaction_hash'], unique=False)
    op.drop_index(op.f('ix_claim_transactions_id'), table_name='claim_transactions')
    op.drop_index(op.f('ix_claim_transactions_transaction_hash'), table_name='claim_transactions')
    op.drop_table('claim_transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount_claimed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('transaction_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('claim_transactions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('claim_transactions_pkey'))
    )
    op.create_index(op.f('ix_claim_transactions_transaction_hash'), 'claim_transactions', ['transaction_hash'], unique=False)
    op.create_index(op.f('ix_claim_transactions_id'), 'claim_transactions', ['id'], unique=False)
    op.drop_index(op.f('ix_batch_payouts_transaction_hash'), table_name='batch_payouts')
    op.drop_index(op.f('ix_batch_payouts_id'), table_name='batch_payouts')
    op.drop_table('batch_payouts')
    op.drop_index(op.f('ix_payout_batches_id'), table_name='payout_batches')
    op.drop_table('payout_batches')
    # ### end Alembic commands ###
