"""Add PersonalAccessToken model and fix has_contributed nullable

Revision ID: <your_revision_id_here>
Revises: 232d57a1d555
Create Date: ...

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '<your_revision_id_here>' # Make sure this matches the filename
down_revision: Union[str, None] = '232d57a1d555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Use batch mode to handle SQLite limitations for altering columns
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('has_contributed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default=sa.text('0')) # Use server_default to handle existing NULLs

    op.create_table('personal_access_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_access_tokens_id'), 'personal_access_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_personal_access_tokens_token_hash'), 'personal_access_tokens', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personal_access_tokens_token_hash'), table_name='personal_access_tokens')
    op.drop_index(op.f('ix_personal_access_tokens_id'), table_name='personal_access_tokens')
    op.drop_table('personal_access_tokens')

    # Use batch mode for downgrade as well
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('has_contributed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               server_default=None) # Remove server default
    # ### end Alembic commands ###