"""Add solana_address to User model

Revision ID: a398557309a7
Revises: a98f6c6a10ee
Create Date: 2025-06-23 13:40:42.046362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a398557309a7'
down_revision: Union[str, None] = 'a98f6c6a10ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('solana_address', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_solana_address'), 'users', ['solana_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_solana_address'), table_name='users')
    op.drop_column('users', 'solana_address')
    # ### end Alembic commands ###
