"""Remove google_id from user

Revision ID: b1c2d3e4f5a6
Revises: e1b2c3d4a5f6
Create Date: 2024-05-21 16:30:45.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c2d3e4f5a6'
down_revision: Union[str, None] = 'e1b2c3d4a5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_google_id_key', 'users', type_='unique')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_google_id_key', 'users', ['google_id'])
    # ### end Alembic commands ###