"""Add 2FA disable token to User

Revision ID: d3a2b1c0f4e5
Revises: 45d12a3b987c
Create Date: 2025-06-25 14:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3a2b1c0f4e5'
down_revision: Union[str, None] = '45d12a3b987c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('two_factor_disable_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('two_factor_disable_expires', sa.Float(), nullable=True))
    op.create_unique_constraint('uq_users_two_factor_disable_token', 'users', ['two_factor_disable_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_two_factor_disable_token', 'users', type_='unique')
    op.drop_column('users', 'two_factor_disable_expires')
    op.drop_column('users', 'two_factor_disable_token')
    # ### end Alembic commands ###