"""Add deletion token to user

Revision ID: e1b2c3d4a5f6
Revises: e2f4a5b6c7d8
Create Date: 2025-06-27 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1b2c3d4a5f6'
down_revision: Union[str, None] = 'e2f4a5b6c7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deletion_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('deletion_token_expires', sa.Float(), nullable=True))
    op.create_unique_constraint(op.f('uq_users_deletion_token'), 'users', ['deletion_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_deletion_token'), 'users', type_='unique')
    op.drop_column('users', 'deletion_token_expires')
    op.drop_column('users', 'deletion_token')
    # ### end Alembic commands ###