"""Dissociate contributions on user delete

Revision ID: e2f4a5b6c7d8
Revises: d3a2b1c0f4e5
Create Date: 2025-06-26 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f4a5b6c7d8'
down_revision: Union[str, None] = 'd3a2b1c0f4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contributions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('contributions_user_id_fkey', 'contributions', type_='foreignkey')
    op.create_foreign_key('contributions_user_id_fkey', 'contributions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contributions_user_id_fkey', 'contributions', type_='foreignkey')
    op.create_foreign_key('contributions_user_id_fkey', 'contributions', 'users', ['user_id'], ['id'])
    op.alter_column('contributions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###