"""Add status to Contribution and is_in_leaderboard to User

Revision ID: ec53005300c6
Revises: 6837691c889e
Create Date: 2025-06-18 14:55:38.897774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec53005300c6'
down_revision: Union[str, None] = '6837691c889e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False, server_default='PENDING'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        # For Boolean columns in SQLite, a common practice for server_default is using sa.text('0') or sa.text('1')
        batch_op.add_column(sa.Column('is_in_leaderboard', sa.Boolean(), nullable=False, server_default=sa.text('1')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_in_leaderboard')

    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.drop_column('status')
    # ### end Alembic commands ###